title: "Blog de Seguridad"
description: "Blog personal para aprender y compartir hacking web"
baseurl: "" # dejar vacío si el repo se llama usuario.github.io
url: "https://b3xal.github.io" # cambia por tu usuario

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
